# Generated by Django 3.1.3 on 2023-11-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=100)),
                ('p_contents', models.TextField()),
                ('p_created', models.DateTimeField(auto_now_add=True)),
                ('p_updated', models.DateTimeField(auto_now=True)),
                ('p_secure', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=20)),
                ('u_pw', models.CharField(max_length=20)),
                ('u_name', models.CharField(max_length=10)),
                ('u_school', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_user_id', models.CharField(max_length=20)),
                ('c_user_pw', models.CharField(max_length=20)),
                ('c_contents', models.TextField()),
                ('c_created', models.DateTimeField(auto_now_add=True)),
                ('c_updated', models.DateTimeField(auto_now=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.post')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=50)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.post')),
            ],
        ),
    ]
