# Generated by Django 3.1.3 on 2023-11-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='p_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mypage.category'),
        ),
    ]
