# Generated by Django 4.2.7 on 2023-11-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
