# Generated by Django 5.0 on 2023-12-19 06:36

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_delete_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_contents',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
